name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          java-package: jdk
          architecture: x64

      - name: Test with gradle
        run: |
          gradle test

      - name: Build
        run: |
          gradle clean build

      - name: Publish package
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: gradle publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
